server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
      tracking-modes: cookie
  compression:
    enabled: true


app:
  name: styleshare-cart

jwt:
  header: Authorization
  expires_in: 86400 # 24hour
  secret: styleshareCart

spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: true

#local 환경
---
spring:
  profiles: local

  datasource:
    data: classpath:data-h2.sql
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
      username: sa
      password:
  jpa:
    database-platform: H2
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.default_batch_fetch_size: 1000
  h2:
    console:
      enabled: true
      path: /console


